const TEAM_REPUTATION_WEIGHT = 0.4;
const TEAM_STANDING_WEIGHT = 0.3;
const TEAM_SHAPE_WEIGHT = 0.2;
const HOME_WEIGHT = 0.1;

const VICTORY_POINTS = 3;
const DRAW_POINTS = 1;

export {
  TEAM_REPUTATION_WEIGHT,
  TEAM_STANDING_WEIGHT,
  TEAM_SHAPE_WEIGHT,
  HOME_WEIGHT,
  VICTORY_POINTS,
  DRAW_POINTS,
};
